# config/dev.yaml
# Конфигурация для разработки
profile: dev
debug: true
log_level: DEBUG
log_dir: logs/dev
data_dir: data/dev
llm_providers:
  default_llm:
    type_provider: llama_cpp
    model_name: qwen-4b
    enabled: true
    parameters:
      model_path: "C:\\Users\\Алексей\\Documents\\WORK\\llm_models\\Qwen3\\Qwen3-4B-Instruct-2507-F16.gguf"
      n_gpu_layers: 0
      n_ctx: 20480
      n_batch: 1024
      temperature: 0.2
      max_tokens: 262100
      verbose: false
      stop: ["<|im_end|>", "<|endoftext|>"]
db_providers:
  default_db:
    type_provider: postgres
    enabled: true
    parameters:
      host: "localhost"
      port: 5432
      database: "postgres"
      username: "postgres"
      password: "1"
      sslmode: "disable"
      timeout: 30.0
      pool_size: 5
skills:
  planning:
    enabled: true
  book_library:
    enabled: true
    parameters:
      max_books_per_search: 10
tools:
  SQLTool:
    enabled: true
  file_tool:
    enabled: true
security:
  secrets_path: config/secrets_dev.yaml